#!/usr/bin/env sh
# Add your pre-commit checks here. For example:
# echo "Running Samoyed sample pre-commit"
# exit 0
cargo fmt --check

cargo test

cd vetis

cargo test --features "http1 tokio-rt tokio-rust-tls static-files reverse-proxy" --no-default-features
cargo test --features "http2 tokio-rt tokio-rust-tls static-files reverse-proxy" --no-default-features
cargo test --features "http3 tokio-rt tokio-rust-tls static-files reverse-proxy" --no-default-features

cargo test --features "http1 smol-rt smol-rust-tls static-files reverse-proxy" --no-default-features
cargo test --features "http2 smol-rt smol-rust-tls static-files reverse-proxy" --no-default-features
cargo test --features "http3 smol-rt smol-rust-tls static-files reverse-proxy" --no-default-features

cd ..